### ISSUE TITLE
Code style guide violation: Mock Analysis

### ISSUE THREAD

**Issue by fkajose** [socratesjnr/asuu-strike-project#5]
Hello team,

I would like to draw attention to a violation of our code style guide in the mock analysis originally made in this project. Specifically, the mock analysis does not follow the conventions specified in the guide.

To maintain consistency and readability in our codebase, it is important that all code follows the guidelines set out in our style guide. I would like to request that the necessary changes be made to bring the mock code in line with the guide.

Thank you for your attention to this matter.

**Comment by socratesjnr** [comment]
I have reviewed and adjusted the code to suit the code style guide. Kindly review the new pull request I made. Thank you

**Comment by fkajose** [comment]
> 

I'm yet to see the pull request.

**Comment by socratesjnr** [comment]
I think this issue has been sorted.
I will be closing with this comment
